### ISSUE TITLE
FanController constructor truncates "sensorThreshold" to 8 bits.

### ISSUE THREAD

**Issue by MojaveTom** [GiorgioAresu/FanController#11]
**FanController.h**
```
class FanController
{
	public:
		FanController(byte sensorPin, unsigned int sensorThreshold, byte pwmPin = 0);
		void begin();
		unsigned int getSpeed();
		void setDutyCycle(byte dutyCycle);
		byte getDutyCycle();
	private:
		static FanController *_instances[6];
		byte _sensorPin;
		byte _sensorInterruptPin;
		byte _sensorThreshold;       //    <--- aka *uint8_t*
		byte _pwmPin;
		byte _pwmDutyCycle;
		byte _instance;
		unsigned int _lastReading;
		volatile unsigned int _halfRevs;
             . . . 
```
**FanController.cpp**
```
FanController::FanController(byte sensorPin, unsigned int sensorThreshold, byte pwmPin)
{
	_sensorPin = sensorPin;
	_sensorInterruptPin = digitalPinToInterrupt(sensorPin);
	_sensorThreshold = sensorThreshold;      //  <---  assign *unsigned int* to *byte*
	_pwmPin = pwmPin;
	pinMode(pwmPin, OUTPUT);
	_pwmDutyCycle = 100;
}
```

**Comment by GiorgioAresu** [comment]
Hi, thanks for taking the time for opening the issue. Version v1.0.6-rc1 should fix the issue, can you confirm?

**Comment by MojaveTom** [comment]
The code mods appear to fix this issue.  I have run no tests to verify; but the fix is so simple that tests should not be necessary.

**Comment by MojaveTom** [comment]
Sorry I didn’t respond earlier.  I agree the issue seems to be resolved by looking at the code.  I haven’t had need to use that module recently.

Thanks,
Tom

**Comment by GiorgioAresu** [comment]
No problems, I'm not very active either, I just remembered I never promoted
it to stable :) have a nice day

Il sab 25 gen 2020, 16:46 Tom <notifications@github.com> ha scritto:
